"""Legacy auth router retained for compatibility, now backed by secure DB auth."""

from app.api.auth_new import (  # re-export secure implementations
    router,
    RegisterRequest,
    LoginRequest,
    SocialLoginRequest,
    TokenResponse,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    create_access_token,
    get_current_user,
    register,
    login,
    get_me,
    logout,
    get_oauth_url,
    oauth_callback,
    request_password_reset,
    reset_password,
)

__all__ = [
    "router",
    "RegisterRequest",
    "LoginRequest",
    "SocialLoginRequest",
    "TokenResponse",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "create_access_token",
    "get_current_user",
    "register",
    "login",
    "get_me",
    "logout",
    "get_oauth_url",
    "oauth_callback",
    "request_password_reset",
    "reset_password",
]
